# board: [seeeduino_xiao, seeeduino_xiao_ble]
# shield: [revxlp]

include:
  - board:  seeeduino_xiao_ble
    shield: revxlp
    # snippet: studio-rpc-usb-uart
    artifact-name: revxlp_qwerty

  - board:  seeeduino_xiao_ble
    shield: revxlp
    # snippet: studio-rpc-usb-uart
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DLAYOUT=1
    artifact-name: revxlp_qwerty_flip

  - board:  seeeduino_xiao_ble
    shield: revxlp
    # snippet: studio-rpc-usb-uart
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DLAYOUT=2
    artifact-name: revxlp_engram

  - board:  seeeduino_xiao_ble
    shield: revxlp
    # snippet: studio-rpc-usb-uart
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DLAYOUT=3
    artifact-name: revxlp_engrammer

  - board:  seeeduino_xiao_ble
    shield: revxlp
    # snippet: studio-rpc-usb-uart
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DLAYOUT=4
    artifact-name: revxlp_nordrassil 


