name: zmk-build

on:
  push:
    paths:
      - 'config/**'
      - 'build.yaml'
      - '.github/workflows/zmk.yml'
  pull_request:
    paths:
      - 'config/**'
      - 'build.yaml'
      - '.github/workflows/zmk.yml'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: revxlp
